name: Publish Canary Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write # Required for Trusted Publishing (OIDC)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Bumping Dev Version
        run: |
          VERSION="1.0.0-dev.${{ github.run_number }}-${{ github.sha }}"
          
          # Update version in the core package
          cd packages/core
          npm version $VERSION --no-git-tag-version
          cd ../../
          
          # Update version in the CLI package
          cd packages/cli
          npm version $VERSION --no-git-tag-version
          # Also update its dependency on the core package
          npm pkg set dependencies.@qozara/gdocs-schema="$VERSION"
          cd ../../

      - name: Publish Core Package
        run: |
          cd packages/core
          npm publish --provenance --access public --tag dev

      - name: Publish CLI Package
        run: |
          cd packages/cli
          npm publish --provenance --access public --tag dev
